
CREATE DATABASE IF NOT EXISTS ASTRO_DB;
USE DATABASE ASTRO_DB;

CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW VW_NEO_ANALYTICS AS 
WITH CLEANED_NEO AS (
    SELECT 
        NEO_REFERENCE_ID,
        NAME AS ASTEROID_NAME,
        ABSOLUTE_MAGNITUDE_H AS MAGNITUDE,
        ESTIMATED_DIAMETER_MIN_KM,
        ESTIMATED_DIAMETER_MAX_KM,
        
        (ESTIMATED_DIAMETER_MIN_KM + ESTIMATED_DIAMETER_MAX_KM) / 2.0 AS AVG_DIAMETER_KM,
        
        CASE 
            WHEN IS_POTENTIALLY_HAZARDOUS = 'True' THEN 'Hazardous'
            ELSE 'Safe'
        END AS HAZARD_STATUS
    FROM 
        RAW_NEO_DATA
)
SELECT 
    NEO_REFERENCE_ID,
    ASTEROID_NAME,
    MAGNITUDE,
    AVG_DIAMETER_KM,
    HAZARD_STATUS,
    
    RANK() OVER(PARTITION BY HAZARD_STATUS ORDER BY AVG_DIAMETER_KM DESC) AS SIZE_RANK_BY_HAZARD
FROM 
    CLEANED_NEO;

SELECT * FROM VW_NEO_ANALYTICS LIMIT 10;